import Head from 'next/head';
import { useQuery } from 'urql';
import { PRODUCT_QUERY } from '../lib/query';
//components
import Product from '../components/Products';
//styled components
import { Gallery } from '../styles/Gallery';




export default function Home() {
  //Fetching from strapi
  const [results] = useQuery({query: PRODUCT_QUERY});
  const {data, fetching, error} = results;

  //check for the data coming in
  if(fetching) return <p>Loading...</p>
  if(error) return <p>Error: {error.message}</p>
  //end of check

  const products = data.products.data;
  
  return (
    <div>
      <Head>
        <title>dmpop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>

      <main>

        <Gallery>
          {products.map((product) =>( 
            <Product 
              key={product.attributes.Slug}
              product={product}
            />
          ))}
        </Gallery>

      </main>

    </div>
  )
}